package entity_hibernate;
// Generated 17.03.2017 16:15:56 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 * Prosty objekt wygenerowany za pomocy Hibernate z mojej BD
 */
public class Publisher implements java.io.Serializable {

    private Set bookConnectedWith = new HashSet(0);
    private Long id;
    private String publisherName;

    public Publisher() {
    }

    public Publisher(String publisherName) {
        this.publisherName = publisherName;
    }

    public Publisher(String publisherName, Set books) {
        this.publisherName = publisherName;
        this.bookConnectedWith = bookConnectedWith;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPublisherName() {
        return publisherName;
    }

    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }

    public Set getBookConnectedWith() {
        return bookConnectedWith;
    }

    public void setBookConnectedWith(Set bookConnectedWith) {
        this.bookConnectedWith = bookConnectedWith;
    }

}
